/**
 * @fileoverview gRPC-Web generated client stub for tokensvc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: ikipb/iki_iam/tokensvc/token.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as ikipb_iki_iam_tokensvc_token_pb from '../../../ikipb/iki_iam/tokensvc/token_pb';


export class TokenClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetJwkset = new grpcWeb.MethodDescriptor(
    '/tokensvc.Token/GetJwkset',
    grpcWeb.MethodType.UNARY,
    ikipb_iki_iam_tokensvc_token_pb.GetJwksetRequest,
    ikipb_iki_iam_tokensvc_token_pb.GetJwksetResponse,
    (request: ikipb_iki_iam_tokensvc_token_pb.GetJwksetRequest) => {
      return request.serializeBinary();
    },
    ikipb_iki_iam_tokensvc_token_pb.GetJwksetResponse.deserializeBinary
  );

  getJwkset(
    request: ikipb_iki_iam_tokensvc_token_pb.GetJwksetRequest,
    metadata: grpcWeb.Metadata | null): Promise<ikipb_iki_iam_tokensvc_token_pb.GetJwksetResponse>;

  getJwkset(
    request: ikipb_iki_iam_tokensvc_token_pb.GetJwksetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: ikipb_iki_iam_tokensvc_token_pb.GetJwksetResponse) => void): grpcWeb.ClientReadableStream<ikipb_iki_iam_tokensvc_token_pb.GetJwksetResponse>;

  getJwkset(
    request: ikipb_iki_iam_tokensvc_token_pb.GetJwksetRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: ikipb_iki_iam_tokensvc_token_pb.GetJwksetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/tokensvc.Token/GetJwkset',
        request,
        metadata || {},
        this.methodDescriptorGetJwkset,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/tokensvc.Token/GetJwkset',
    request,
    metadata || {},
    this.methodDescriptorGetJwkset);
  }

  methodDescriptorAccessToken = new grpcWeb.MethodDescriptor(
    '/tokensvc.Token/AccessToken',
    grpcWeb.MethodType.UNARY,
    ikipb_iki_iam_tokensvc_token_pb.AccessTokenRequest,
    ikipb_iki_iam_tokensvc_token_pb.AccessTokenResponse,
    (request: ikipb_iki_iam_tokensvc_token_pb.AccessTokenRequest) => {
      return request.serializeBinary();
    },
    ikipb_iki_iam_tokensvc_token_pb.AccessTokenResponse.deserializeBinary
  );

  accessToken(
    request: ikipb_iki_iam_tokensvc_token_pb.AccessTokenRequest,
    metadata: grpcWeb.Metadata | null): Promise<ikipb_iki_iam_tokensvc_token_pb.AccessTokenResponse>;

  accessToken(
    request: ikipb_iki_iam_tokensvc_token_pb.AccessTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: ikipb_iki_iam_tokensvc_token_pb.AccessTokenResponse) => void): grpcWeb.ClientReadableStream<ikipb_iki_iam_tokensvc_token_pb.AccessTokenResponse>;

  accessToken(
    request: ikipb_iki_iam_tokensvc_token_pb.AccessTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: ikipb_iki_iam_tokensvc_token_pb.AccessTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/tokensvc.Token/AccessToken',
        request,
        metadata || {},
        this.methodDescriptorAccessToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/tokensvc.Token/AccessToken',
    request,
    metadata || {},
    this.methodDescriptorAccessToken);
  }

}

