/**
 * @fileoverview gRPC-Web generated client stub for heatmap
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: ikipb/iki_heatmap/heatmap.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.heatmap = require('./heatmap_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.heatmap.HeatmapServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.heatmap.HeatmapServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.heatmap.GetRequest,
 *   !proto.heatmap.Track>}
 */
const methodDescriptor_HeatmapService_Get = new grpc.web.MethodDescriptor(
  '/heatmap.HeatmapService/Get',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.heatmap.GetRequest,
  proto.heatmap.Track,
  /**
   * @param {!proto.heatmap.GetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.heatmap.Track.deserializeBinary
);


/**
 * @param {!proto.heatmap.GetRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.heatmap.Track>}
 *     The XHR Node Readable Stream
 */
proto.heatmap.HeatmapServiceClient.prototype.get =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/heatmap.HeatmapService/Get',
      request,
      metadata || {},
      methodDescriptor_HeatmapService_Get);
};


/**
 * @param {!proto.heatmap.GetRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.heatmap.Track>}
 *     The XHR Node Readable Stream
 */
proto.heatmap.HeatmapServicePromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/heatmap.HeatmapService/Get',
      request,
      metadata || {},
      methodDescriptor_HeatmapService_Get);
};


module.exports = proto.heatmap;

