// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ikipb/iki_blog/categorysvc/categorysvc.proto

package categorysvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategorySvc_List_FullMethodName = "/categorysvc.CategorySvc/List"
)

// CategorySvcClient is the client API for CategorySvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategorySvcClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type categorySvcClient struct {
	cc grpc.ClientConnInterface
}

func NewCategorySvcClient(cc grpc.ClientConnInterface) CategorySvcClient {
	return &categorySvcClient{cc}
}

func (c *categorySvcClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, CategorySvc_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategorySvcServer is the server API for CategorySvc service.
// All implementations must embed UnimplementedCategorySvcServer
// for forward compatibility.
type CategorySvcServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedCategorySvcServer()
}

// UnimplementedCategorySvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategorySvcServer struct{}

func (UnimplementedCategorySvcServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCategorySvcServer) mustEmbedUnimplementedCategorySvcServer() {}
func (UnimplementedCategorySvcServer) testEmbeddedByValue()                     {}

// UnsafeCategorySvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategorySvcServer will
// result in compilation errors.
type UnsafeCategorySvcServer interface {
	mustEmbedUnimplementedCategorySvcServer()
}

func RegisterCategorySvcServer(s grpc.ServiceRegistrar, srv CategorySvcServer) {
	// If the following call panics, it indicates UnimplementedCategorySvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategorySvc_ServiceDesc, srv)
}

func _CategorySvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategorySvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategorySvc_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategorySvcServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategorySvc_ServiceDesc is the grpc.ServiceDesc for CategorySvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategorySvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "categorysvc.CategorySvc",
	HandlerType: (*CategorySvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CategorySvc_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ikipb/iki_blog/categorysvc/categorysvc.proto",
}
