// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ikipb/iki_activity/activitysvc/activity.proto

package activitysvc

import (
	iki_activity "github.com/ikithomas/iki-proto/ikipb/iki_activity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyRequest) Reset() {
	*x = GetMyRequest{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyRequest) ProtoMessage() {}

func (x *GetMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyRequest.ProtoReflect.Descriptor instead.
func (*GetMyRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{0}
}

func (x *GetMyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *iki_activity.Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyResponse) Reset() {
	*x = GetMyResponse{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyResponse) ProtoMessage() {}

func (x *GetMyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyResponse.ProtoReflect.Descriptor instead.
func (*GetMyResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyResponse) GetActivity() *iki_activity.Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ListMyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRequest) Reset() {
	*x = ListMyRequest{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRequest) ProtoMessage() {}

func (x *ListMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRequest.ProtoReflect.Descriptor instead.
func (*ListMyRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{2}
}

func (x *ListMyRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMyResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Activities    []*iki_activity.Activity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	TotalCount    int64                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyResponse) Reset() {
	*x = ListMyResponse{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyResponse) ProtoMessage() {}

func (x *ListMyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyResponse.ProtoReflect.Descriptor instead.
func (*ListMyResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{3}
}

func (x *ListMyResponse) GetActivities() []*iki_activity.Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ListMyResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CalculateMyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateMyStatsRequest) Reset() {
	*x = CalculateMyStatsRequest{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateMyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMyStatsRequest) ProtoMessage() {}

func (x *CalculateMyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMyStatsRequest.ProtoReflect.Descriptor instead.
func (*CalculateMyStatsRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{4}
}

type CalculateMyStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateMyStatsResponse) Reset() {
	*x = CalculateMyStatsResponse{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateMyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMyStatsResponse) ProtoMessage() {}

func (x *CalculateMyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMyStatsResponse.ProtoReflect.Descriptor instead.
func (*CalculateMyStatsResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{5}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *iki_activity.Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetActivity() *iki_activity.Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Activities    []*iki_activity.Activity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	TotalCount    int64                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetActivities() []*iki_activity.Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CalculateStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStatsRequest) Reset() {
	*x = CalculateStatsRequest{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStatsRequest) ProtoMessage() {}

func (x *CalculateStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStatsRequest.ProtoReflect.Descriptor instead.
func (*CalculateStatsRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{10}
}

func (x *CalculateStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CalculateStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStatsResponse) Reset() {
	*x = CalculateStatsResponse{}
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStatsResponse) ProtoMessage() {}

func (x *CalculateStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStatsResponse.ProtoReflect.Descriptor instead.
func (*CalculateStatsResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP(), []int{11}
}

var File_ikipb_iki_activity_activitysvc_activity_proto protoreflect.FileDescriptor

const file_ikipb_iki_activity_activitysvc_activity_proto_rawDesc = "" +
	"\n" +
	"-ikipb/iki_activity/activitysvc/activity.proto\x12\vactivitysvc\x1a!ikipb/iki_activity/activity.proto\"\x1e\n" +
	"\fGetMyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\rGetMyResponse\x12.\n" +
	"\bactivity\x18\x01 \x01(\v2\x12.activity.ActivityR\bactivity\"@\n" +
	"\rListMyRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"e\n" +
	"\x0eListMyResponse\x122\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x12.activity.ActivityR\n" +
	"activities\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x19\n" +
	"\x17CalculateMyStatsRequest\"\x1a\n" +
	"\x18CalculateMyStatsResponse\"5\n" +
	"\n" +
	"GetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"=\n" +
	"\vGetResponse\x12.\n" +
	"\bactivity\x18\x01 \x01(\v2\x12.activity.ActivityR\bactivity\"W\n" +
	"\vListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"c\n" +
	"\fListResponse\x122\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x12.activity.ActivityR\n" +
	"activities\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"0\n" +
	"\x15CalculateStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x18\n" +
	"\x16CalculateStatsResponse2\xf3\x01\n" +
	"\rMyActivitySvc\x12>\n" +
	"\x03Get\x12\x19.activitysvc.GetMyRequest\x1a\x1a.activitysvc.GetMyResponse\"\x00\x12A\n" +
	"\x04List\x12\x1a.activitysvc.ListMyRequest\x1a\x1b.activitysvc.ListMyResponse\"\x00\x12_\n" +
	"\x0eCalculateStats\x12$.activitysvc.CalculateMyStatsRequest\x1a%.activitysvc.CalculateMyStatsResponse\"\x002\xe5\x01\n" +
	"\vActivitySvc\x12:\n" +
	"\x03Get\x12\x17.activitysvc.GetRequest\x1a\x18.activitysvc.GetResponse\"\x00\x12=\n" +
	"\x04List\x12\x18.activitysvc.ListRequest\x1a\x19.activitysvc.ListResponse\"\x00\x12[\n" +
	"\x0eCalculateStats\x12\".activitysvc.CalculateStatsRequest\x1a#.activitysvc.CalculateStatsResponse\"\x00B\x0eZ\f/activitysvcb\x06proto3"

var (
	file_ikipb_iki_activity_activitysvc_activity_proto_rawDescOnce sync.Once
	file_ikipb_iki_activity_activitysvc_activity_proto_rawDescData []byte
)

func file_ikipb_iki_activity_activitysvc_activity_proto_rawDescGZIP() []byte {
	file_ikipb_iki_activity_activitysvc_activity_proto_rawDescOnce.Do(func() {
		file_ikipb_iki_activity_activitysvc_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ikipb_iki_activity_activitysvc_activity_proto_rawDesc), len(file_ikipb_iki_activity_activitysvc_activity_proto_rawDesc)))
	})
	return file_ikipb_iki_activity_activitysvc_activity_proto_rawDescData
}

var file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ikipb_iki_activity_activitysvc_activity_proto_goTypes = []any{
	(*GetMyRequest)(nil),             // 0: activitysvc.GetMyRequest
	(*GetMyResponse)(nil),            // 1: activitysvc.GetMyResponse
	(*ListMyRequest)(nil),            // 2: activitysvc.ListMyRequest
	(*ListMyResponse)(nil),           // 3: activitysvc.ListMyResponse
	(*CalculateMyStatsRequest)(nil),  // 4: activitysvc.CalculateMyStatsRequest
	(*CalculateMyStatsResponse)(nil), // 5: activitysvc.CalculateMyStatsResponse
	(*GetRequest)(nil),               // 6: activitysvc.GetRequest
	(*GetResponse)(nil),              // 7: activitysvc.GetResponse
	(*ListRequest)(nil),              // 8: activitysvc.ListRequest
	(*ListResponse)(nil),             // 9: activitysvc.ListResponse
	(*CalculateStatsRequest)(nil),    // 10: activitysvc.CalculateStatsRequest
	(*CalculateStatsResponse)(nil),   // 11: activitysvc.CalculateStatsResponse
	(*iki_activity.Activity)(nil),    // 12: activity.Activity
}
var file_ikipb_iki_activity_activitysvc_activity_proto_depIdxs = []int32{
	12, // 0: activitysvc.GetMyResponse.activity:type_name -> activity.Activity
	12, // 1: activitysvc.ListMyResponse.activities:type_name -> activity.Activity
	12, // 2: activitysvc.GetResponse.activity:type_name -> activity.Activity
	12, // 3: activitysvc.ListResponse.activities:type_name -> activity.Activity
	0,  // 4: activitysvc.MyActivitySvc.Get:input_type -> activitysvc.GetMyRequest
	2,  // 5: activitysvc.MyActivitySvc.List:input_type -> activitysvc.ListMyRequest
	4,  // 6: activitysvc.MyActivitySvc.CalculateStats:input_type -> activitysvc.CalculateMyStatsRequest
	6,  // 7: activitysvc.ActivitySvc.Get:input_type -> activitysvc.GetRequest
	8,  // 8: activitysvc.ActivitySvc.List:input_type -> activitysvc.ListRequest
	10, // 9: activitysvc.ActivitySvc.CalculateStats:input_type -> activitysvc.CalculateStatsRequest
	1,  // 10: activitysvc.MyActivitySvc.Get:output_type -> activitysvc.GetMyResponse
	3,  // 11: activitysvc.MyActivitySvc.List:output_type -> activitysvc.ListMyResponse
	5,  // 12: activitysvc.MyActivitySvc.CalculateStats:output_type -> activitysvc.CalculateMyStatsResponse
	7,  // 13: activitysvc.ActivitySvc.Get:output_type -> activitysvc.GetResponse
	9,  // 14: activitysvc.ActivitySvc.List:output_type -> activitysvc.ListResponse
	11, // 15: activitysvc.ActivitySvc.CalculateStats:output_type -> activitysvc.CalculateStatsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ikipb_iki_activity_activitysvc_activity_proto_init() }
func file_ikipb_iki_activity_activitysvc_activity_proto_init() {
	if File_ikipb_iki_activity_activitysvc_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ikipb_iki_activity_activitysvc_activity_proto_rawDesc), len(file_ikipb_iki_activity_activitysvc_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ikipb_iki_activity_activitysvc_activity_proto_goTypes,
		DependencyIndexes: file_ikipb_iki_activity_activitysvc_activity_proto_depIdxs,
		MessageInfos:      file_ikipb_iki_activity_activitysvc_activity_proto_msgTypes,
	}.Build()
	File_ikipb_iki_activity_activitysvc_activity_proto = out.File
	file_ikipb_iki_activity_activitysvc_activity_proto_goTypes = nil
	file_ikipb_iki_activity_activitysvc_activity_proto_depIdxs = nil
}
