// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ikipb/iki_blog/filesvc/filesvc.proto

package filesvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadMyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// base64 bytes
	Body          string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMyRequest) Reset() {
	*x = UploadMyRequest{}
	mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMyRequest) ProtoMessage() {}

func (x *UploadMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMyRequest.ProtoReflect.Descriptor instead.
func (*UploadMyRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadMyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadMyRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UploadMyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMyResponse) Reset() {
	*x = UploadMyResponse{}
	mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMyResponse) ProtoMessage() {}

func (x *UploadMyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMyResponse.ProtoReflect.Descriptor instead.
func (*UploadMyResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMyResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_ikipb_iki_blog_filesvc_filesvc_proto protoreflect.FileDescriptor

const file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc = "" +
	"\n" +
	"$ikipb/iki_blog/filesvc/filesvc.proto\x12\afilesvc\"M\n" +
	"\x0fUploadMyRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"$\n" +
	"\x10UploadMyResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2L\n" +
	"\tMyFileSvc\x12?\n" +
	"\x06Upload\x12\x18.filesvc.UploadMyRequest\x1a\x19.filesvc.UploadMyResponse\"\x00B\x1fZ\b/filesvc\xea\x02\x12Iki::Blog::FileSvcb\x06proto3"

var (
	file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescOnce sync.Once
	file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescData []byte
)

func file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescGZIP() []byte {
	file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescOnce.Do(func() {
		file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc), len(file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc)))
	})
	return file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescData
}

var file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ikipb_iki_blog_filesvc_filesvc_proto_goTypes = []any{
	(*UploadMyRequest)(nil),  // 0: filesvc.UploadMyRequest
	(*UploadMyResponse)(nil), // 1: filesvc.UploadMyResponse
}
var file_ikipb_iki_blog_filesvc_filesvc_proto_depIdxs = []int32{
	0, // 0: filesvc.MyFileSvc.Upload:input_type -> filesvc.UploadMyRequest
	1, // 1: filesvc.MyFileSvc.Upload:output_type -> filesvc.UploadMyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ikipb_iki_blog_filesvc_filesvc_proto_init() }
func file_ikipb_iki_blog_filesvc_filesvc_proto_init() {
	if File_ikipb_iki_blog_filesvc_filesvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc), len(file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ikipb_iki_blog_filesvc_filesvc_proto_goTypes,
		DependencyIndexes: file_ikipb_iki_blog_filesvc_filesvc_proto_depIdxs,
		MessageInfos:      file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes,
	}.Build()
	File_ikipb_iki_blog_filesvc_filesvc_proto = out.File
	file_ikipb_iki_blog_filesvc_filesvc_proto_goTypes = nil
	file_ikipb_iki_blog_filesvc_filesvc_proto_depIdxs = nil
}
