// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: ikipb/iki_blog/filesvc/filesvc.proto

package filesvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadMyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UploadMyRequest) Reset() {
	*x = UploadMyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMyRequest) ProtoMessage() {}

func (x *UploadMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMyRequest.ProtoReflect.Descriptor instead.
func (*UploadMyRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadMyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadMyRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type UploadMyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UploadMyResponse) Reset() {
	*x = UploadMyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMyResponse) ProtoMessage() {}

func (x *UploadMyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMyResponse.ProtoReflect.Descriptor instead.
func (*UploadMyResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMyResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_ikipb_iki_blog_filesvc_filesvc_proto protoreflect.FileDescriptor

var file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6b, 0x69, 0x70, 0x62, 0x2f, 0x69, 0x6b, 0x69, 0x5f, 0x62, 0x6c, 0x6f, 0x67,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x76, 0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x76, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x76, 0x63, 0x22,
	0x4d, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x24,
	0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x32, 0x4c, 0x0a, 0x09, 0x4d, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x76,
	0x63, 0x12, 0x3f, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x76, 0x63, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x76, 0x63, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x76, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescOnce sync.Once
	file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescData = file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc
)

func file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescGZIP() []byte {
	file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescOnce.Do(func() {
		file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescData)
	})
	return file_ikipb_iki_blog_filesvc_filesvc_proto_rawDescData
}

var file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ikipb_iki_blog_filesvc_filesvc_proto_goTypes = []interface{}{
	(*UploadMyRequest)(nil),  // 0: filesvc.UploadMyRequest
	(*UploadMyResponse)(nil), // 1: filesvc.UploadMyResponse
}
var file_ikipb_iki_blog_filesvc_filesvc_proto_depIdxs = []int32{
	0, // 0: filesvc.MyFileSvc.Upload:input_type -> filesvc.UploadMyRequest
	1, // 1: filesvc.MyFileSvc.Upload:output_type -> filesvc.UploadMyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ikipb_iki_blog_filesvc_filesvc_proto_init() }
func file_ikipb_iki_blog_filesvc_filesvc_proto_init() {
	if File_ikipb_iki_blog_filesvc_filesvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ikipb_iki_blog_filesvc_filesvc_proto_goTypes,
		DependencyIndexes: file_ikipb_iki_blog_filesvc_filesvc_proto_depIdxs,
		MessageInfos:      file_ikipb_iki_blog_filesvc_filesvc_proto_msgTypes,
	}.Build()
	File_ikipb_iki_blog_filesvc_filesvc_proto = out.File
	file_ikipb_iki_blog_filesvc_filesvc_proto_rawDesc = nil
	file_ikipb_iki_blog_filesvc_filesvc_proto_goTypes = nil
	file_ikipb_iki_blog_filesvc_filesvc_proto_depIdxs = nil
}
