/**
 * @fileoverview gRPC-Web generated client stub for activity
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: ikipb/iki_activity/activity.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.activity = require('./activity_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.activity.ActivityServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.activity.ActivityServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.activity.GetRequest,
 *   !proto.activity.GetResponse>}
 */
const methodDescriptor_ActivityService_Get = new grpc.web.MethodDescriptor(
  '/activity.ActivityService/Get',
  grpc.web.MethodType.UNARY,
  proto.activity.GetRequest,
  proto.activity.GetResponse,
  /**
   * @param {!proto.activity.GetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.activity.GetResponse.deserializeBinary
);


/**
 * @param {!proto.activity.GetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.activity.GetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.activity.GetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.activity.ActivityServiceClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/activity.ActivityService/Get',
      request,
      metadata || {},
      methodDescriptor_ActivityService_Get,
      callback);
};


/**
 * @param {!proto.activity.GetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.activity.GetResponse>}
 *     Promise that resolves to the response
 */
proto.activity.ActivityServicePromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/activity.ActivityService/Get',
      request,
      metadata || {},
      methodDescriptor_ActivityService_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.activity.ListRequest,
 *   !proto.activity.ListResponse>}
 */
const methodDescriptor_ActivityService_List = new grpc.web.MethodDescriptor(
  '/activity.ActivityService/List',
  grpc.web.MethodType.UNARY,
  proto.activity.ListRequest,
  proto.activity.ListResponse,
  /**
   * @param {!proto.activity.ListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.activity.ListResponse.deserializeBinary
);


/**
 * @param {!proto.activity.ListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.activity.ListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.activity.ListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.activity.ActivityServiceClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/activity.ActivityService/List',
      request,
      metadata || {},
      methodDescriptor_ActivityService_List,
      callback);
};


/**
 * @param {!proto.activity.ListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.activity.ListResponse>}
 *     Promise that resolves to the response
 */
proto.activity.ActivityServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/activity.ActivityService/List',
      request,
      metadata || {},
      methodDescriptor_ActivityService_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.activity.GetMineRequest,
 *   !proto.activity.GetMineResponse>}
 */
const methodDescriptor_ActivityService_GetMine = new grpc.web.MethodDescriptor(
  '/activity.ActivityService/GetMine',
  grpc.web.MethodType.UNARY,
  proto.activity.GetMineRequest,
  proto.activity.GetMineResponse,
  /**
   * @param {!proto.activity.GetMineRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.activity.GetMineResponse.deserializeBinary
);


/**
 * @param {!proto.activity.GetMineRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.activity.GetMineResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.activity.GetMineResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.activity.ActivityServiceClient.prototype.getMine =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/activity.ActivityService/GetMine',
      request,
      metadata || {},
      methodDescriptor_ActivityService_GetMine,
      callback);
};


/**
 * @param {!proto.activity.GetMineRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.activity.GetMineResponse>}
 *     Promise that resolves to the response
 */
proto.activity.ActivityServicePromiseClient.prototype.getMine =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/activity.ActivityService/GetMine',
      request,
      metadata || {},
      methodDescriptor_ActivityService_GetMine);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.activity.ListMineRequest,
 *   !proto.activity.ListMineResponse>}
 */
const methodDescriptor_ActivityService_ListMine = new grpc.web.MethodDescriptor(
  '/activity.ActivityService/ListMine',
  grpc.web.MethodType.UNARY,
  proto.activity.ListMineRequest,
  proto.activity.ListMineResponse,
  /**
   * @param {!proto.activity.ListMineRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.activity.ListMineResponse.deserializeBinary
);


/**
 * @param {!proto.activity.ListMineRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.activity.ListMineResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.activity.ListMineResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.activity.ActivityServiceClient.prototype.listMine =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/activity.ActivityService/ListMine',
      request,
      metadata || {},
      methodDescriptor_ActivityService_ListMine,
      callback);
};


/**
 * @param {!proto.activity.ListMineRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.activity.ListMineResponse>}
 *     Promise that resolves to the response
 */
proto.activity.ActivityServicePromiseClient.prototype.listMine =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/activity.ActivityService/ListMine',
      request,
      metadata || {},
      methodDescriptor_ActivityService_ListMine);
};


module.exports = proto.activity;

