/**
 * @fileoverview gRPC-Web generated client stub for activity
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: ikipb/iki_activity/activity.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.activity = require('./activity_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.activity.ActivityServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.activity.ActivityServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.activity.GetActivityRequest,
 *   !proto.activity.GetActivityResponse>}
 */
const methodDescriptor_ActivityService_Get = new grpc.web.MethodDescriptor(
  '/activity.ActivityService/Get',
  grpc.web.MethodType.UNARY,
  proto.activity.GetActivityRequest,
  proto.activity.GetActivityResponse,
  /**
   * @param {!proto.activity.GetActivityRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.activity.GetActivityResponse.deserializeBinary
);


/**
 * @param {!proto.activity.GetActivityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.activity.GetActivityResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.activity.GetActivityResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.activity.ActivityServiceClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/activity.ActivityService/Get',
      request,
      metadata || {},
      methodDescriptor_ActivityService_Get,
      callback);
};


/**
 * @param {!proto.activity.GetActivityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.activity.GetActivityResponse>}
 *     Promise that resolves to the response
 */
proto.activity.ActivityServicePromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/activity.ActivityService/Get',
      request,
      metadata || {},
      methodDescriptor_ActivityService_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.activity.ListActivityRequest,
 *   !proto.activity.ListActivityResponse>}
 */
const methodDescriptor_ActivityService_List = new grpc.web.MethodDescriptor(
  '/activity.ActivityService/List',
  grpc.web.MethodType.UNARY,
  proto.activity.ListActivityRequest,
  proto.activity.ListActivityResponse,
  /**
   * @param {!proto.activity.ListActivityRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.activity.ListActivityResponse.deserializeBinary
);


/**
 * @param {!proto.activity.ListActivityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.activity.ListActivityResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.activity.ListActivityResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.activity.ActivityServiceClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/activity.ActivityService/List',
      request,
      metadata || {},
      methodDescriptor_ActivityService_List,
      callback);
};


/**
 * @param {!proto.activity.ListActivityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.activity.ListActivityResponse>}
 *     Promise that resolves to the response
 */
proto.activity.ActivityServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/activity.ActivityService/List',
      request,
      metadata || {},
      methodDescriptor_ActivityService_List);
};


module.exports = proto.activity;

