/**
 * @fileoverview gRPC-Web generated client stub for authsvc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: ikipb/iki_iam/authsvc/auth.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var ikipb_iki_iam_iam_pb = require('../../../ikipb/iki_iam/iam_pb.js')
const proto = {};
proto.authsvc = require('./auth_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authsvc.AuthClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authsvc.AuthPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authsvc.GoogleLoginRequest,
 *   !proto.authsvc.GoogleLoginResponse>}
 */
const methodDescriptor_Auth_GoogleLogin = new grpc.web.MethodDescriptor(
  '/authsvc.Auth/GoogleLogin',
  grpc.web.MethodType.UNARY,
  proto.authsvc.GoogleLoginRequest,
  proto.authsvc.GoogleLoginResponse,
  /**
   * @param {!proto.authsvc.GoogleLoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authsvc.GoogleLoginResponse.deserializeBinary
);


/**
 * @param {!proto.authsvc.GoogleLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authsvc.GoogleLoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authsvc.GoogleLoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authsvc.AuthClient.prototype.googleLogin =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authsvc.Auth/GoogleLogin',
      request,
      metadata || {},
      methodDescriptor_Auth_GoogleLogin,
      callback);
};


/**
 * @param {!proto.authsvc.GoogleLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authsvc.GoogleLoginResponse>}
 *     Promise that resolves to the response
 */
proto.authsvc.AuthPromiseClient.prototype.googleLogin =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authsvc.Auth/GoogleLogin',
      request,
      metadata || {},
      methodDescriptor_Auth_GoogleLogin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authsvc.ServiceLoginRequest,
 *   !proto.authsvc.ServiceLoginResponse>}
 */
const methodDescriptor_Auth_ServiceLogin = new grpc.web.MethodDescriptor(
  '/authsvc.Auth/ServiceLogin',
  grpc.web.MethodType.UNARY,
  proto.authsvc.ServiceLoginRequest,
  proto.authsvc.ServiceLoginResponse,
  /**
   * @param {!proto.authsvc.ServiceLoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authsvc.ServiceLoginResponse.deserializeBinary
);


/**
 * @param {!proto.authsvc.ServiceLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authsvc.ServiceLoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authsvc.ServiceLoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authsvc.AuthClient.prototype.serviceLogin =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authsvc.Auth/ServiceLogin',
      request,
      metadata || {},
      methodDescriptor_Auth_ServiceLogin,
      callback);
};


/**
 * @param {!proto.authsvc.ServiceLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authsvc.ServiceLoginResponse>}
 *     Promise that resolves to the response
 */
proto.authsvc.AuthPromiseClient.prototype.serviceLogin =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authsvc.Auth/ServiceLogin',
      request,
      metadata || {},
      methodDescriptor_Auth_ServiceLogin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authsvc.SignoutRequest,
 *   !proto.authsvc.SignoutResponse>}
 */
const methodDescriptor_Auth_Signout = new grpc.web.MethodDescriptor(
  '/authsvc.Auth/Signout',
  grpc.web.MethodType.UNARY,
  proto.authsvc.SignoutRequest,
  proto.authsvc.SignoutResponse,
  /**
   * @param {!proto.authsvc.SignoutRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authsvc.SignoutResponse.deserializeBinary
);


/**
 * @param {!proto.authsvc.SignoutRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authsvc.SignoutResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authsvc.SignoutResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authsvc.AuthClient.prototype.signout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authsvc.Auth/Signout',
      request,
      metadata || {},
      methodDescriptor_Auth_Signout,
      callback);
};


/**
 * @param {!proto.authsvc.SignoutRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authsvc.SignoutResponse>}
 *     Promise that resolves to the response
 */
proto.authsvc.AuthPromiseClient.prototype.signout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authsvc.Auth/Signout',
      request,
      metadata || {},
      methodDescriptor_Auth_Signout);
};


module.exports = proto.authsvc;

