// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: ikipb/iki_iam/authsvc/auth.proto

package authsvc

import (
	iki_iam "github.com/ikithomas/iki-proto/ikipb/iki_iam"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoogleLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginRequest) Reset() {
	*x = GoogleLoginRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginRequest) ProtoMessage() {}

func (x *GoogleLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginRequest.ProtoReflect.Descriptor instead.
func (*GoogleLoginRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleLoginRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type GoogleLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	User          *iki_iam.User          `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginResponse) Reset() {
	*x = GoogleLoginResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginResponse) ProtoMessage() {}

func (x *GoogleLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginResponse.ProtoReflect.Descriptor instead.
func (*GoogleLoginResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GoogleLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GoogleLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GoogleLoginResponse) GetUser() *iki_iam.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ServiceLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLoginRequest) Reset() {
	*x = ServiceLoginRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLoginRequest) ProtoMessage() {}

func (x *ServiceLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLoginRequest.ProtoReflect.Descriptor instead.
func (*ServiceLoginRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceLoginRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ServiceLoginRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type ServiceLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLoginResponse) Reset() {
	*x = ServiceLoginResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLoginResponse) ProtoMessage() {}

func (x *ServiceLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLoginResponse.ProtoReflect.Descriptor instead.
func (*ServiceLoginResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ServiceLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type SignoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignoutRequest) Reset() {
	*x = SignoutRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignoutRequest) ProtoMessage() {}

func (x *SignoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignoutRequest.ProtoReflect.Descriptor instead.
func (*SignoutRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{4}
}

type SignoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignoutResponse) Reset() {
	*x = SignoutResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignoutResponse) ProtoMessage() {}

func (x *SignoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignoutResponse.ProtoReflect.Descriptor instead.
func (*SignoutResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{5}
}

type BeginPasskeyRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPasskeyRegistrationRequest) Reset() {
	*x = BeginPasskeyRegistrationRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPasskeyRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPasskeyRegistrationRequest) ProtoMessage() {}

func (x *BeginPasskeyRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPasskeyRegistrationRequest.ProtoReflect.Descriptor instead.
func (*BeginPasskeyRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{6}
}

type BeginPasskeyRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionsJson   string                 `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPasskeyRegistrationResponse) Reset() {
	*x = BeginPasskeyRegistrationResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPasskeyRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPasskeyRegistrationResponse) ProtoMessage() {}

func (x *BeginPasskeyRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPasskeyRegistrationResponse.ProtoReflect.Descriptor instead.
func (*BeginPasskeyRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{7}
}

func (x *BeginPasskeyRegistrationResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

func (x *BeginPasskeyRegistrationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FinishPasskeyRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CredentialJson string                 `protobuf:"bytes,2,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinishPasskeyRegistrationRequest) Reset() {
	*x = FinishPasskeyRegistrationRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishPasskeyRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPasskeyRegistrationRequest) ProtoMessage() {}

func (x *FinishPasskeyRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPasskeyRegistrationRequest.ProtoReflect.Descriptor instead.
func (*FinishPasskeyRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{8}
}

func (x *FinishPasskeyRegistrationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinishPasskeyRegistrationRequest) GetCredentialJson() string {
	if x != nil {
		return x.CredentialJson
	}
	return ""
}

type FinishPasskeyRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishPasskeyRegistrationResponse) Reset() {
	*x = FinishPasskeyRegistrationResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishPasskeyRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPasskeyRegistrationResponse) ProtoMessage() {}

func (x *FinishPasskeyRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPasskeyRegistrationResponse.ProtoReflect.Descriptor instead.
func (*FinishPasskeyRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{9}
}

type BeginPasskeyLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPasskeyLoginRequest) Reset() {
	*x = BeginPasskeyLoginRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPasskeyLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPasskeyLoginRequest) ProtoMessage() {}

func (x *BeginPasskeyLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPasskeyLoginRequest.ProtoReflect.Descriptor instead.
func (*BeginPasskeyLoginRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{10}
}

func (x *BeginPasskeyLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type BeginPasskeyLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionsJson   string                 `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPasskeyLoginResponse) Reset() {
	*x = BeginPasskeyLoginResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPasskeyLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPasskeyLoginResponse) ProtoMessage() {}

func (x *BeginPasskeyLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPasskeyLoginResponse.ProtoReflect.Descriptor instead.
func (*BeginPasskeyLoginResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{11}
}

func (x *BeginPasskeyLoginResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

func (x *BeginPasskeyLoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FinishPasskeyLoginRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CredentialJson string                 `protobuf:"bytes,2,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinishPasskeyLoginRequest) Reset() {
	*x = FinishPasskeyLoginRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishPasskeyLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPasskeyLoginRequest) ProtoMessage() {}

func (x *FinishPasskeyLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPasskeyLoginRequest.ProtoReflect.Descriptor instead.
func (*FinishPasskeyLoginRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{12}
}

func (x *FinishPasskeyLoginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinishPasskeyLoginRequest) GetCredentialJson() string {
	if x != nil {
		return x.CredentialJson
	}
	return ""
}

type FinishPasskeyLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	User          *iki_iam.User          `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishPasskeyLoginResponse) Reset() {
	*x = FinishPasskeyLoginResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishPasskeyLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPasskeyLoginResponse) ProtoMessage() {}

func (x *FinishPasskeyLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPasskeyLoginResponse.ProtoReflect.Descriptor instead.
func (*FinishPasskeyLoginResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{13}
}

func (x *FinishPasskeyLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *FinishPasskeyLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *FinishPasskeyLoginResponse) GetUser() *iki_iam.User {
	if x != nil {
		return x.User
	}
	return nil
}

type Passkey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerName     string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Identifier    string                 `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *int64                 `protobuf:"varint,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passkey) Reset() {
	*x = Passkey{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passkey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passkey) ProtoMessage() {}

func (x *Passkey) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passkey.ProtoReflect.Descriptor instead.
func (*Passkey) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{14}
}

func (x *Passkey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Passkey) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Passkey) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Passkey) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Passkey) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Passkey) GetLastUsedAt() int64 {
	if x != nil && x.LastUsedAt != nil {
		return *x.LastUsedAt
	}
	return 0
}

type ListPasskeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPasskeysRequest) Reset() {
	*x = ListPasskeysRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPasskeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPasskeysRequest) ProtoMessage() {}

func (x *ListPasskeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPasskeysRequest.ProtoReflect.Descriptor instead.
func (*ListPasskeysRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ListPasskeysRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type ListPasskeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passkeys      []*Passkey             `protobuf:"bytes,1,rep,name=passkeys,proto3" json:"passkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPasskeysResponse) Reset() {
	*x = ListPasskeysResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPasskeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPasskeysResponse) ProtoMessage() {}

func (x *ListPasskeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPasskeysResponse.ProtoReflect.Descriptor instead.
func (*ListPasskeysResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ListPasskeysResponse) GetPasskeys() []*Passkey {
	if x != nil {
		return x.Passkeys
	}
	return nil
}

type DeletePasskeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePasskeyRequest) Reset() {
	*x = DeletePasskeyRequest{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePasskeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePasskeyRequest) ProtoMessage() {}

func (x *DeletePasskeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePasskeyRequest.ProtoReflect.Descriptor instead.
func (*DeletePasskeyRequest) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePasskeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePasskeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePasskeyResponse) Reset() {
	*x = DeletePasskeyResponse{}
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePasskeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePasskeyResponse) ProtoMessage() {}

func (x *DeletePasskeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePasskeyResponse.ProtoReflect.Descriptor instead.
func (*DeletePasskeyResponse) Descriptor() ([]byte, []int) {
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP(), []int{18}
}

var File_ikipb_iki_iam_authsvc_auth_proto protoreflect.FileDescriptor

var file_ikipb_iki_iam_authsvc_auth_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x69, 0x6b, 0x69, 0x70, 0x62, 0x2f, 0x69, 0x6b, 0x69, 0x5f, 0x69, 0x61, 0x6d, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x1a, 0x17, 0x69, 0x6b, 0x69,
	0x70, 0x62, 0x2f, 0x69, 0x6b, 0x69, 0x5f, 0x69, 0x61, 0x6d, 0x2f, 0x69, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7c, 0x0a, 0x13, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x57, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x5e, 0x0a, 0x14,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x10, 0x0a, 0x0e,
	0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11,
	0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x21, 0x0a, 0x1f, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65,
	0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x64, 0x0a, 0x20, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73,
	0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x20, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x21, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x18, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x5d, 0x0a,
	0x19, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x19,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x4a, 0x73, 0x6f,
	0x6e, 0x22, 0x83, 0x01, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73,
	0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0xca, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x73, 0x73,
	0x6b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x25, 0x0a, 0x0c,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x64, 0x41, 0x74,
	0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x22, 0x3f, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x6b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x6b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65,
	0x79, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73,
	0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xad, 0x06, 0x0a,
	0x07, 0x41, 0x75, 0x74, 0x68, 0x53, 0x76, 0x63, 0x12, 0x4a, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76,
	0x63, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74, 0x12, 0x17,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76,
	0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x18, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73,
	0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x28, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x73, 0x76, 0x63, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50,
	0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x11,
	0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x21, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x12, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65,
	0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x73, 0x76, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73,
	0x6b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x6b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_ikipb_iki_iam_authsvc_auth_proto_rawDescOnce sync.Once
	file_ikipb_iki_iam_authsvc_auth_proto_rawDescData []byte
)

func file_ikipb_iki_iam_authsvc_auth_proto_rawDescGZIP() []byte {
	file_ikipb_iki_iam_authsvc_auth_proto_rawDescOnce.Do(func() {
		file_ikipb_iki_iam_authsvc_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ikipb_iki_iam_authsvc_auth_proto_rawDesc), len(file_ikipb_iki_iam_authsvc_auth_proto_rawDesc)))
	})
	return file_ikipb_iki_iam_authsvc_auth_proto_rawDescData
}

var file_ikipb_iki_iam_authsvc_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ikipb_iki_iam_authsvc_auth_proto_goTypes = []any{
	(*GoogleLoginRequest)(nil),                // 0: authsvc.GoogleLoginRequest
	(*GoogleLoginResponse)(nil),               // 1: authsvc.GoogleLoginResponse
	(*ServiceLoginRequest)(nil),               // 2: authsvc.ServiceLoginRequest
	(*ServiceLoginResponse)(nil),              // 3: authsvc.ServiceLoginResponse
	(*SignoutRequest)(nil),                    // 4: authsvc.SignoutRequest
	(*SignoutResponse)(nil),                   // 5: authsvc.SignoutResponse
	(*BeginPasskeyRegistrationRequest)(nil),   // 6: authsvc.BeginPasskeyRegistrationRequest
	(*BeginPasskeyRegistrationResponse)(nil),  // 7: authsvc.BeginPasskeyRegistrationResponse
	(*FinishPasskeyRegistrationRequest)(nil),  // 8: authsvc.FinishPasskeyRegistrationRequest
	(*FinishPasskeyRegistrationResponse)(nil), // 9: authsvc.FinishPasskeyRegistrationResponse
	(*BeginPasskeyLoginRequest)(nil),          // 10: authsvc.BeginPasskeyLoginRequest
	(*BeginPasskeyLoginResponse)(nil),         // 11: authsvc.BeginPasskeyLoginResponse
	(*FinishPasskeyLoginRequest)(nil),         // 12: authsvc.FinishPasskeyLoginRequest
	(*FinishPasskeyLoginResponse)(nil),        // 13: authsvc.FinishPasskeyLoginResponse
	(*Passkey)(nil),                           // 14: authsvc.Passkey
	(*ListPasskeysRequest)(nil),               // 15: authsvc.ListPasskeysRequest
	(*ListPasskeysResponse)(nil),              // 16: authsvc.ListPasskeysResponse
	(*DeletePasskeyRequest)(nil),              // 17: authsvc.DeletePasskeyRequest
	(*DeletePasskeyResponse)(nil),             // 18: authsvc.DeletePasskeyResponse
	(*iki_iam.User)(nil),                      // 19: iam.User
}
var file_ikipb_iki_iam_authsvc_auth_proto_depIdxs = []int32{
	19, // 0: authsvc.GoogleLoginResponse.user:type_name -> iam.User
	19, // 1: authsvc.FinishPasskeyLoginResponse.user:type_name -> iam.User
	14, // 2: authsvc.ListPasskeysResponse.passkeys:type_name -> authsvc.Passkey
	0,  // 3: authsvc.AuthSvc.GoogleLogin:input_type -> authsvc.GoogleLoginRequest
	2,  // 4: authsvc.AuthSvc.ServiceLogin:input_type -> authsvc.ServiceLoginRequest
	4,  // 5: authsvc.AuthSvc.Signout:input_type -> authsvc.SignoutRequest
	6,  // 6: authsvc.AuthSvc.BeginPasskeyRegistration:input_type -> authsvc.BeginPasskeyRegistrationRequest
	8,  // 7: authsvc.AuthSvc.FinishPasskeyRegistration:input_type -> authsvc.FinishPasskeyRegistrationRequest
	10, // 8: authsvc.AuthSvc.BeginPasskeyLogin:input_type -> authsvc.BeginPasskeyLoginRequest
	12, // 9: authsvc.AuthSvc.FinishPasskeyLogin:input_type -> authsvc.FinishPasskeyLoginRequest
	15, // 10: authsvc.AuthSvc.ListPasskeys:input_type -> authsvc.ListPasskeysRequest
	17, // 11: authsvc.AuthSvc.DeletePasskey:input_type -> authsvc.DeletePasskeyRequest
	1,  // 12: authsvc.AuthSvc.GoogleLogin:output_type -> authsvc.GoogleLoginResponse
	3,  // 13: authsvc.AuthSvc.ServiceLogin:output_type -> authsvc.ServiceLoginResponse
	5,  // 14: authsvc.AuthSvc.Signout:output_type -> authsvc.SignoutResponse
	7,  // 15: authsvc.AuthSvc.BeginPasskeyRegistration:output_type -> authsvc.BeginPasskeyRegistrationResponse
	9,  // 16: authsvc.AuthSvc.FinishPasskeyRegistration:output_type -> authsvc.FinishPasskeyRegistrationResponse
	11, // 17: authsvc.AuthSvc.BeginPasskeyLogin:output_type -> authsvc.BeginPasskeyLoginResponse
	13, // 18: authsvc.AuthSvc.FinishPasskeyLogin:output_type -> authsvc.FinishPasskeyLoginResponse
	16, // 19: authsvc.AuthSvc.ListPasskeys:output_type -> authsvc.ListPasskeysResponse
	18, // 20: authsvc.AuthSvc.DeletePasskey:output_type -> authsvc.DeletePasskeyResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ikipb_iki_iam_authsvc_auth_proto_init() }
func file_ikipb_iki_iam_authsvc_auth_proto_init() {
	if File_ikipb_iki_iam_authsvc_auth_proto != nil {
		return
	}
	file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[14].OneofWrappers = []any{}
	file_ikipb_iki_iam_authsvc_auth_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ikipb_iki_iam_authsvc_auth_proto_rawDesc), len(file_ikipb_iki_iam_authsvc_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ikipb_iki_iam_authsvc_auth_proto_goTypes,
		DependencyIndexes: file_ikipb_iki_iam_authsvc_auth_proto_depIdxs,
		MessageInfos:      file_ikipb_iki_iam_authsvc_auth_proto_msgTypes,
	}.Build()
	File_ikipb_iki_iam_authsvc_auth_proto = out.File
	file_ikipb_iki_iam_authsvc_auth_proto_goTypes = nil
	file_ikipb_iki_iam_authsvc_auth_proto_depIdxs = nil
}
