# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ikipb/iki_blog/blog.proto

require 'google/protobuf'


descriptor_data = "\n\x19ikipb/iki_blog/blog.proto\x12\x04\x62log\"\xb6\x02\n\x0cPostMetadata\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12$\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x0c.blog.AuthorR\x06\x61uthor\x12\x14\n\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n\x07preface\x18\x04 \x01(\tR\x07preface\x12\x1c\n\tpublished\x18\x05 \x01(\x08R\tpublished\x12\x12\n\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n\x08\x63\x61tegory\x18\x07 \x01(\tR\x08\x63\x61tegory\x12\x1d\n\ncreated_at\x18\x08 \x01(\x03R\tcreatedAt\x12\x1d\n\nupdated_at\x18\t \x01(\x03R\tupdatedAt\x12$\n\x0bmagazine_id\x18\n \x01(\tH\x00R\nmagazineId\x88\x01\x01\x42\x0e\n\x0c_magazine_id\"\xca\x01\n\x08Magazine\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12$\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x0c.blog.AuthorR\x06\x61uthor\x12\x14\n\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n\x07preface\x18\x04 \x01(\tR\x07preface\x12\x1a\n\x08\x63\x61tegory\x18\x05 \x01(\tR\x08\x63\x61tegory\x12\x1d\n\ncreated_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n\nupdated_at\x18\x07 \x01(\x03R\tupdatedAt\"[\n\x06\x41uthor\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n\x0biki_user_id\x18\x02 \x01(\tR\tikiUserId\x12!\n\x0c\x64isplay_name\x18\x03 \x01(\tR\x0b\x64isplayName\"=\n\nPagination\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n\tpage_size\x18\x02 \x01(\x05R\x08pageSizeB;Z-github.com/ikithomas/iki-proto/ikipb/iki_blog\xea\x02\tIki::Blogb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Iki
  module Blog
    PostMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.PostMetadata").msgclass
    Magazine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.Magazine").msgclass
    Author = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.Author").msgclass
    Pagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.Pagination").msgclass
  end
end
