# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ikipb/iki_iam/iam.proto

require 'google/protobuf'


descriptor_data = "\n\x17ikipb/iki_iam/iam.proto\x12\x03iam\"\x86\x02\n\x04User\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12\x1d\n\ngiven_name\x18\x03 \x01(\tR\tgivenName\x12\x1f\n\x0b\x66\x61mily_name\x18\x04 \x01(\tR\nfamilyName\x12 \n\x05roles\x18\x08 \x03(\x0b\x32\n.iam.GroupR\x05roles\x12\x16\n\x06\x61\x63tive\x18\t \x01(\x08R\x06\x61\x63tive\x12\"\n\rlast_login_at\x18\n \x01(\x03R\x0blastLoginAt\x12(\n\x10last_activity_at\x18\x0b \x01(\x03R\x0elastActivityAtJ\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08\"+\n\x05Group\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"q\n\x07Service\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\tclient_id\x18\x02 \x01(\tR\x08\x63lientId\x12%\n\x07secrets\x18\x03 \x03(\x0b\x32\x0b.iam.SecretR\x07secrets\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\"j\n\x06Secret\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06secret\x18\x02 \x01(\tR\x06secret\x12 \n\x0clast_used_at\x18\x03 \x01(\x03R\nlastUsedAt\x12\x16\n\x06\x61\x63tive\x18\x04 \x01(\x08R\x06\x61\x63tive*X\n\nEntityType\x12\x1b\n\x17\x45NTITY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x45NTITY_TYPE_USER\x10\x01\x12\x17\n\x13\x45NTITY_TYPE_SERVICE\x10\x02\x42.Z,github.com/ikithomas/iki-proto/ikipb/iki_iamb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Iam
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("iam.User").msgclass
  Group = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("iam.Group").msgclass
  Service = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("iam.Service").msgclass
  Secret = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("iam.Secret").msgclass
  EntityType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("iam.EntityType").enummodule
end
